### ISSUE TITLE
Could not open input file: ./artisan

### ISSUE THREAD

**Issue by iraldoad** [hitalos/laravel#28]
Hello @hitalos.
I am trying to use your image but it returns the same error that #17 and #3 . I'm using Docker Desktop on Windows. This is the docker-compose.yml file:

```yml
web:
  image: hitalos/laravel:latest
  container_name: pay_web
  ports:
    - 80:80
  volumes:
    - ./:/var/www
  links:
    - db
  environment:
    DB_HOST: db
    DB_DATABASE: dbname
    DB_USERNAME: username
    DB_PASSWORD: p455w0rd
    DB_CONNECTION: mysql
db:
  image: mysql
  container_name: pay_db
  environment:
    MYSQL_DATABASE: dbname
    MYSQL_USER: username
    MYSQL_ROOT_PASSWORD: p455w0rd
```
